namespace PulseWidget.Models;

public sealed record SensorSnapshot(
    DateTime Timestamp,
    string CpuName,
    string GpuName,
    double? CpuUsage,
    double? CpuTemperature,
    double? CpuPower,
    double? CpuClock,
    double? GpuUsage,
    double? GpuTemperature,
    double? GpuPower,
    double? GpuClock,
    double? GpuMemoryUsedMb,
    double? GpuMemoryTotalMb,
    double? MemoryUsage,
    double? MemoryUsedGb,
    double? MemoryAvailableGb,
    string StorageName,
    double? StorageTemperature,
    double? StorageActivity,
    string FanName,
    double? FanRpm,
    string NetworkName,
    double? NetworkDownloadBytes,
    double? NetworkUploadBytes,
    string Status);
